package tek.bdd.runner;

// Import the necessary classes from Cucumber and JUnit libraries
import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;



// This annotation tells JUnit to run the tests using Cucumber
@RunWith(Cucumber.class)
@CucumberOptions(
        // Specifies the location of the feature files. "classpath:features" means it looks in the "features" folder located in the classpath
        features = "classpath:features",
        // Specifies the package containing the step definitions
        glue = "tek.bdd.steps",
        // Filters which scenarios to run based on tags. Here, only scenarios tagged with "@Smoke" will be executed
        tags = "@Smoke",
        // If true, it will only check if the feature files and step definitions are correctly linked, without running the tests
        dryRun = false,
        // If true, the console output will be more readable (without ANSI colors or other formatting)
        monochrome = true,
        // Specifies the format of the step definition snippets generated by Cucumber. CAMELCASE means they will use CamelCase format
        snippets = CucumberOptions.SnippetType.CAMELCASE,
        // Specifies the plugins used for reporting and console output
        plugin = {
                // Generates an HTML report in the specified location
                "html:target/cucumber-report/report.html",

                // Provides a pretty print of the test execution results in the console
                "pretty",
        }
)
// This is the main runner class for Cucumber tests. It doesn’t contain any methods or fields because it is only used to configure and run the tests
public class TestRunner {
}